source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

inhibit_all_warnings!

use_frameworks!

target 'TTTFramework-Example' do
  pod 'TTTFramework', :path => '../', :isSource => true
  # pod 'TTTFramework'

end
